# fly.toml file generated for api-forest-rpg on 2022-10-04T05:25:20+08:00

app = "api-forest-rpg"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  MONGO_HOST="testdb1.nse0a.mongodb.net"
  MONGO_DB_NAME="obtainer"
  MONGO_USERNAME="albertnotes"
  MONGO_PASSWORD="qaz123wsx456"
  JWT_SECRET="8xc&|iE{W+$6t2h2|l5Q%C*5m?+%|tMF]k!Pv{:H{JPgmn=_2ef7h<hrM-o4x[H;"
  JWT_EXPIRES_DAY="7d"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
